### ISSUE TITLE
Find out the IP of dgplug.org

### ISSUE THREAD

**Issue by kushaldas** [kushaldas/lymworkbook#1]
Find out the IP of dgplug.org and put into `/tmp/ip_dgplug.txt` file.

**Comment by Priyankasaggu11929** [comment]
@kushaldas I want to work on this issue.

**Comment by sap143** [comment]
> Find out the IP of dgplug.org and put into `/tmp/ip_dgplug.txt` file.
I will work on this problem

**Comment by kushaldas** [comment]
Fixed at https://github.com/kushaldas/lymworkbook/commit/e69190311423cc4bb35819a73dcf404128ea5af8
